service: nothungry-api
runtime: custom
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
dispatch:
  - url: api.nothungry.com.br/* # e.g. subdomain.example.com/*
    service: nothungry-api