version: '3'

services:
  db:
    container_name: postgres-nothungry
    image: postgres:11
    restart: unless-stopped
    volumes:
      - postgres-nothungry-data:/data
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS} 
    networks:
      - app-connect

  nodejs-nothungry:
    container_name: nodejs-nothungry
    build: '.'
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - db
    networks:
      - app-connect
    ports:
      - '8080:80'
    environment: 
      DB_HOST: db

volumes:
  postgres-nothungry-data:

networks:
  app-connect:
      driver: bridge